#!/bin/bash

tmux new-session -d -s PipefyApp
tmux split-window -t PipefyApp
tmux split-window  -h -t PipefyApp
sleep 2

tmux send-keys -t PipefyApp:1.1 'gopipe' 'C-m'
tmux send-keys -t PipefyApp:1.1 'docker-up' 'C-m'

tmux send-keys -t PipefyApp:1.2 'gopipe' 'C-m'
tmux send-keys -t PipefyApp:1.2 'bin/rails s' 'C-m'

tmux send-keys -t PipefyApp:1.3 'gopipe' 'C-m'
tmux send-keys -t PipefyApp:1.3 'bin/sidekiq' 'C-m'

